default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: 12345

development:
  <<: *default
  database: store_manager_development

test:
  <<: *default
  database: store_manager_test

production:
  <<: *default
  database: store_manager_production
  username: store_manager
  password: <%= ENV["STORE_MANAGER_DATABASE_PASSWORD"] %>
